require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'assignmentTask' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'assignmentTaskTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'assignmentTask-tvOS' do
  # Pods for assignmentTask-tvOS

  target 'assignmentTask-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
